# Generated by Django 4.0.4 on 2023-02-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Categories:')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL:')),
            ],
            options={
                'verbose_name': 'Category of task:',
                'verbose_name_plural': 'Categorys of tasks:',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task name:')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL:')),
                ('content', models.TextField(blank=True, verbose_name='Text of task:')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Time of update:')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done:')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published:')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.category', verbose_name='Category:')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['title'],
            },
        ),
    ]
