# Generated by Django 4.0.4 on 2023-01-25 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
