# Generated by Django 4.0.4 on 2023-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_category_todolistitem_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category of task:', 'verbose_name_plural': 'Category of tasks:'},
        ),
        migrations.AlterModelOptions(
            name='todolistitem',
            options={'ordering': ['title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category of task:'),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Task name:'),
        ),
    ]
